<a href="https://colab.research.google.com/github/ASi-F/NLPlay-Checkpoint-1/blob/main/PyTorch_tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# **Initialising stuff-**

In [ ]:
# from a normal array
x = [[1,2,3],[3,2,1]]
tensor = torch.tensor(x)

In [ ]:
print(tensor)

tensor([[1, 2, 3],
        [3, 2, 1]])


In [ ]:
# from a np array
x = np.array([[1,0,1],[0,1,0]])
tensor = torch.from_numpy(x)
print(tensor)

tensor([[1, 0, 1],
        [0, 1, 0]])


In [ ]:
# initialising with random values, zeros or ones
tensor = torch.rand((2,3))
print(tensor)
tensor = torch.zeros((2))
print(tensor)
tensor = torch.ones((3,2,1))
print(tensor)

tensor([[0.0343, 0.3295, 0.8626],
        [0.8032, 0.6273, 0.9940]])
tensor([0., 0.])
tensor([[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]])


## Attributes
tensor.shape returns tuple of tensor shape<br>
tensor.dtype returns dtype of tensor<br>
tensor.device returns device in which tensor is stored<br>

In [ ]:
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 2, 1])
torch.float32
cpu


In [ ]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
print(tensor.device)

cuda:0


In [ ]:
tensor = torch.ones(4,4)
print(tensor,'\n')
tensor[:,1] = 0
print(tensor,'\n')
tensor = torch.cat([tensor,tensor,tensor],dim=1)
print(tensor,'\n')

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) 



In [ ]:
print(tensor.T,'\n')
print(tensor*tensor,'\n')
print(tensor@tensor.T,'\n')

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) 

tensor([[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]]) 



# **In place ops**
Operations ending with _ are inplace operations <br>
x.t_() <br>
x.copy_(y) <br>


In [ ]:
x = torch.rand((4,2))
y = torch.ones((4,1))
print(x)
print(y)
print(x+y)

tensor([[0.9454, 0.3434],
        [0.2965, 0.7695],
        [0.6840, 0.3692],
        [0.8240, 0.0660]])
tensor([[1.],
        [1.],
        [1.],
        [1.]])
tensor([[1.9454, 1.3434],
        [1.2965, 1.7695],
        [1.6840, 1.3692],
        [1.8240, 1.0660]])


In [ ]:
x = torch.rand(3,4,5)
print(x)
print(x.sum())
print(x.sum(dim = 0))
print(x.sum(dim = 1))
print(x.sum(dim = 2))
print(x.sum(dim = (0,1)))
print(x.sum(dim = (1,2)))
print(x.sum(dim = (0,2)))
print(x.sum(dim = (0,1,2)))

tensor([[[0.2521, 0.8084, 0.9212, 0.8924, 0.6319],
         [0.0561, 0.6650, 0.4296, 0.6740, 0.9614],
         [0.2180, 0.5940, 0.3509, 0.4922, 0.3092],
         [0.3671, 0.6613, 0.4344, 0.4397, 0.6879]],

        [[0.1363, 0.3298, 0.2771, 0.4911, 0.8162],
         [0.6256, 0.0043, 0.4404, 0.4605, 0.3078],
         [0.2833, 0.9658, 0.7286, 0.0064, 0.0725],
         [0.0062, 0.1180, 0.3359, 0.0818, 0.4544]],

        [[0.3863, 0.0064, 0.8394, 0.4274, 0.9206],
         [0.5537, 0.2623, 0.1774, 0.1294, 0.0704],
         [0.8749, 0.7157, 0.3490, 0.7758, 0.4273],
         [0.9148, 0.9897, 0.8856, 0.4894, 0.4394]]])
tensor(28.4234)
tensor([[0.7747, 1.1446, 2.0377, 1.8110, 2.3686],
        [1.2354, 0.9316, 1.0474, 1.2639, 1.3395],
        [1.3762, 2.2755, 1.4284, 1.2745, 0.8091],
        [1.2881, 1.7690, 1.6559, 1.0108, 1.5816]])
tensor([[0.8933, 2.7286, 2.1361, 2.4983, 2.5903],
        [1.0514, 1.4179, 1.7819, 1.0398, 1.6509],
        [2.7296, 1.9741, 2.2514, 1.8220, 1.8576]])
tensor([[3.506